### ISSUE TITLE
Assertion failing on debugging perls

### ISSUE THREAD

**Issue by andk** [ingydotnet/yaml-libyaml-pm#109]
Sample fail report: http://www.cpantesters.org/cpan/report/8fac74a6-ebc8-11ed-91d1-e1766b9e9f2a

**Comment by perlpunk** [comment]
I wonder if we even need that `assert`. It looks like it works without it.
But maybe we should just add a `SvPOK_on(key_node)` before it?

**Comment by perlpunk** [comment]
There is an issue about creating debugging container images: https://github.com/Perl/docker-perl/issues/130
So as soon as this is out, we can use such an image, and we would have catched this error in CI already...

**Comment by perlpunk** [comment]
A fix: #110

**Comment by perlpunk** [comment]
This was fixed for now by the revert (#112) of #107
