### ISSUE TITLE
Legacy bundled Test::Builder causes superfluous warnings on 5.19+ (RT93309)

### ISSUE THREAD

**Issue by nawglan** [ingydotnet/yaml-libyaml-pm#13]
Looks similar to https://rt.cpan.org/Ticket/Display.html?id=90185 and is probably the case for anything you bundle Test::Builder with really.

Test::Builder 0.98
https://metacpan.org/source/INGY/YAML-LibYAML-0.41/inc/Test/Builder.pm#L8

PERL_DL_NONLAZY=1 /home/kent/perl5/perlbrew/perls/perl-5.19.9-fast/bin/perl5.19.9 "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef _Test::Harness::Switches; test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/_.t
Possible precedence issue with control flow operator at /home/kent/.cpanm/work/1393251373.733713/YAML-LibYAML-0.41/inc/Test/Builder.pm line 917.
t/alias.t ............ ok
Possible precedence issue with control flow operator at /home/kent/.cpanm/work/1393251373.733713/YAML-LibYAML-0.41/inc/Test/Builder.pm line 917.
t/api.t .............. ok
Possible precedence issue with control flow operator at /home/kent/.cpanm/work/1393251373.733713/YAML-LibYAML-0.41/inc/Test/Builder.pm line 917.
t/ascii.t ............ ok
Possible precedence issue with control flow operator at /home/kent/.cpanm/work/1393251373.733713/YAML-LibYAML-0.41/inc/Test/Builder.pm line 917.
t/blessed.t .......... ok

x a bunch.

**Comment by nawglan** [comment]
original RT ticket: https://rt.cpan.org/Ticket/Display.html?id=93309

**Comment by nawglan** [comment]
These were fixed in Test::Builder.  So imbedding a newer Test::Builder should be the recommended solution.

0.98_06  Fri Sep 27 10:11:05 EDT 2013
    Bug Fixes
    * Fix precedence error with (return ... and ...)
      (nthykier) [github #385]

**Comment by perlpunk** [comment]
I think this can be closed since Test::Builder isn't used anymore.
