### ISSUE TITLE
Load() and utf8.pm don't play nice. (RT54683)

### ISSUE THREAD

**Issue by nawglan** [ingydotnet/yaml-libyaml-pm#15]
The attached program demonstrates utf8 and YAML::XS don't mix.

```perl
#!/usr/bin/perl

use utf8;
use YAML::XS qw(Load);

my $yaml =q[
Ævar Arnfjörð Bjarmason:
  - avar@cpan.org
  - avarab@gmail.com
];

Load($yaml);
print "Done\n";
```
I get:
```
YAML::XS::Load Error: The problem:

    Invalid trailing UTF-8 octet

was found at document: 0
```

With a wide character, like so:

```
my $yaml =q[
貞廣知行:
  - bqw10602@nifty.com
];
```
I get:
Wide character in subroutine entry at yourfile line 11.

edit @perlpunk 2016-07-02: marked code sections

**Comment by perlpunk** [comment]
YAML::XS wants encoded strings. `use utf8` automatically decodes strings inside of the script, so if you feed those to Load, you have to encode it again first.
```
Load(encode_utf8 $yaml);
```
So I'm closing this issue, but feel free to reopen if necessary.
