### ISSUE TITLE
Multiple documents are ignored when loading a YAML file (RT82833)

### ISSUE THREAD

**Issue by nawglan** [ingydotnet/yaml-libyaml-pm#16]
YAML::XS v0.38 appears to only load the last-encountered document in a 
YAML file rather than providing access to all of them.

Example YML file "test.yml":
```
---
documentNr:    1
...
---
documentNr:    2
...
```
Observe the following behaviour of YAML::XS compared to YAML::Tiny. This 
is running Perl v5.8.8 on RHEL 5 x86_64.

```
$ perl -e 'use Data::Dumper; use YAML::Any qw/LoadFile/; my $x = 
LoadFile("test.yml"); print Dumper($x);'
$VAR1 = {
           'documentNr' => 2
         };

$ perl -e 'use Data::Dumper; use YAML::Tiny; my $x = 
YAML::Tiny->read("test.yml"); print Dumper($x);'
$VAR1 = bless( [
                  {
                    'documentNr' => '1'
                  },
                  {
                    'documentNr' => '2'
                  }
                ], 'YAML::Tiny');
$
```

There is no apparent way of getting to the first document when using 
YAML::XS to parse it. I'm not familiar with libyaml, so I can't tell 
whether this is due to the underlying implementation or due to any 
post-processing by YAML::XS. Feel free to defer to libyaml's bug 
tracking if this problem is ultimately due to libyaml.

2016-02-23 edit @perlpunk: markup code for better readability

**Comment by perlpunk** [comment]
fwiw, if you call LoadFile in list context, you will get all documents. This also works for YAML.pm.
It's bad that YAML::Tiny work different, though. And that it's not documented.

**Comment by perlpunk** [comment]
Actually, it is documented. YAML::XS points to YAML. While the documentation for the Load function doesn't say anything about context, the SYNOPSIS example uses list context. But maybe it's not clear enough?

So I'll close this for now. If you have suggestions about improving the documentation or if this doesn't work for you, feel free to reopen.
