### ISSUE TITLE
new line inserted when exceeding some amount of characters

### ISSUE THREAD

**Issue by rahed** [ingydotnet/yaml-libyaml-pm#29]
When dumping the following structure, the Dump function returns yaml but inserts "\n" after _|_No attempt to find.

use YAML::XS;
  $output = {
         'DETAIL' => {
              'digital_(Digital_test)' => 'No attempt to find out correct results_|_No attempt to find out correct results',
             }
        };
print Dump($output);

Do I have to set something or is it a bug?  No such behaviour if using only YAML.

**Comment by perlpunk** [comment]
This is the intended behavior. libyaml tries to keep lines short. If you Load it back, it will load as the original data. (If not, please reopen the issue.)
There's no way to configure this, as far as I can see.
