### ISSUE TITLE
what is error 'YAML::XS Error: Expected STREAM_START_EVENT; Got: 0 != 1'

### ISSUE THREAD

**Issue by godsarmy** [ingydotnet/yaml-libyaml-pm#34]
I uses YAML::XS to load YAML string. It is fine in the beginning. But after about 300K times calling Load, Load stops working with error message 'YAML::XS Error: Expected STREAM_START_EVENT; Got: 0 != 1' forever. My YAML::XS version is 0.59

Has anyone encountered this issue?

**Comment by godsarmy** [comment]
It seems if error being caught by large number of times, Load stop working.

Sample test code

'''
use YAML::XS qw/ Load /;

sub yaml_2_json {
    my ($str) = @_;

    eval {
        my ($obj) = Load($str);
    };
    if ($@) {
        # in this case, we return the orignal string
        print "$@ failed to convert YAML string: $str";
        if ($@ =~ /STREAM_START_EVENT/) {
            exit 1;
        }
    }
}

my $str = join('', <DATA>);

for (my $i = 0; $i < 5000000; $i++) {
    print "\n$i\n";
    yaml_2_json($str);
}

__DATA__
---
_error:
  foo: bar
  aaa
'''

result:
'''
<....>
61569
YAML::XS::Load Error: The problem:

    could not find expected ':'

was found at document: 1, line: 5, column: 1
while scanning a simple key at line: 4, column: 3
 failed to convert YAML string: ---
_error:
  foo: bar
  aaa

61570
YAML::XS Error: Expected STREAM_START_EVENT; Got: 0 != 1 at ./y2j.pl line 20, <DATA> line 4.
 failed to convert YAML string: ---
_error:
  foo: bar
  aaa
'''

**Comment by subogero** [comment]
Error reproduced, in my case this is the full error message:

    63529
    YAML::XS Error: Expected STREAM_START_EVENT; Got: 0 != 1 at ./xs line 24, <DATA> line 4.
    Out of memory!

**Comment by subogero** [comment]
The number of iterations until the error does not seem to depend on the size of the erroneous YAML.

**Comment by perlpunk** [comment]
Yeah, there is a memory leak.
The biggest problem is that `yaml_parser_delete()` isn't called in case of an error.
But also after adding it, it still leaks, though a lot less.
My C/XS knowledge isn't good enough to see where the other leaks are, and how to handle this. The code currently simply calls `croak` which bypasses the code for cleaning up.

**Comment by subogero** [comment]
I straced the test case, the memory leak is very obvious. All you can see is the `brk()` system calls with ever increasing upper limits on virtual memory. Eventually it fails, then Perl tries to `mmap` some memory, that fails too, and so on. At the end it gets a SIGKILL from the kernel.

    brk(0x13fe81d000)                       = 0x13fe81d000
    brk(0x13fe83f000)                       = 0x13fe81d000
    mmap(NULL, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
    mmap(NULL, 134217728, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x7fb3c815d000
    munmap(0x7fb3c815d000, 65679360)        = 0
    munmap(0x7fb3d0000000, 1429504)         = 0
    mprotect(0x7fb3cc000000, 184320, PROT_READ|PROT_WRITE) = 0
    ...
    +++ killed by SIGKILL +++
    Killed

**Comment by perlpunk** [comment]
@godsarmy I wasn't able to reproduce your error.

@subogero Maybe you can try out my pull request #48 

I added `notes/memleak.pl`

**Comment by subogero** [comment]
Thank you. Yes, I'll try to test your pull request.

**Comment by subogero** [comment]
How can I easily build and install YAML::XS locally?

**Comment by perlpunk** [comment]
Oh, yes, that's a bit more complicated than usual.
First, you have to install Zilla::Dist. Then, do:
```
# create a CPAN distribution directory
% zild distdir
% cd YAML-LibYAML-0.62
% perl Makefile.PL
% make
# You can now use blib directly to test it or do make test/make install
% perl -Mblib ../note/memleak.pl ...
```

**Comment by subogero** [comment]
Zilla::Dist is a no-no. It depends on all imaginable meta-meta-meta-meta Perl modules of the galaxy. I installed it with cpanm. I spent an hour with it only to find out that CPAN has no reliable method for uninstalling packages, and no method at all to uninstall automatically installed dependencies. So I deleted the entire `/usr/local/lib/perl` directory.

Meanwhile I found the way to "easily build and install YAML::XS locally":

    # The arch dependent binaries go to /usr/local/lib/perl
    cd LibYAML
    # Remove the part from Makefile.PL that calls update.sh
    perl Makefile.PL
    make
    sudo make install
    # The arch independent pure Perl parts go to /usr/share/perl5
    cd ../lib
    sudo cp -r YAML /usr/share/perl5

The good news is that after your excellent fix, my memleak test case does not break any more. Yesterday it broke after trying to Load the invalid YAML about 1.2 million times.

After the fix, I'm now at 13 million iterations, and it's still going strong.

Thank you! I'm sure some big American investment banks will be very excited too. :)

**Comment by perlpunk** [comment]
Yeah, Zilla::Dist/Dist::Zilla have a *huge* dependency chain :-/

It's easy for pure perl modules to work around this (with Dist::Zilla) and copy generated files like Makefile.PL into the source for every build, but I haven't tried that for XS modules and with Zilla::Dist.

Good to hear this fix works for you. I think the remaining leaks arent't that critical any more, but I hope someone else can have a look at that.

@ingydotnet would you be ok with a trial release? don't know how to do that with Zilla::Dist, though.

**Comment by subogero** [comment]
33 million iterations. Still running... :)

**Comment by subogero** [comment]
My process got killed after 58 million iterations to load an invalid YAML. So yes, there are other minor memory leaks, but this fix is a *huge* improvement.

**Comment by perlpunk** [comment]
Thanks for testing.

Now I think I found the remaining leak \o/
I had suspected it but hadn't found the right place to do the cleanup. Did 10000 iterations and memory usage stayed the same. Will update the pull request =)

**Comment by subogero** [comment]
BTW, here is my test script, which is an infinite loop and always displays the iteration number at the top and if it breaks with STREAM_START_EVENT, it displays the last two errors.

    #!/usr/bin/perl
    use YAML::XS;
    
    my $yml = <<EOF;
    ---
    good: line
    badline
    EOF
    
    my $i = 0;
    my $err_last;
    while (++$i) {
        print "\r$i";
        my $data = eval { Load $yml };
        if (my $err = $@) {
            if ($err =~ /STREAM_START_EVENT/) {
                print "\r$i\n";
                print "$err_last\n";
                print "$err\n";
                exit;
            }
            $err_last = $err;
        }
    }

**Comment by perlpunk** [comment]
@subogero we did a developer release 0.62_002 with the fix

**Comment by subogero** [comment]
Thank you very much, this is excellent news!

**Comment by subogero** [comment]
Do you know when 0.63 might be available on CPAN?

**Comment by perlpunk** [comment]
@subogero I would like to wait for a few more test reports: http://matrix.cpantesters.org/?dist=YAML-LibYAML+0.62_002
so maybe in a couple of days...

**Comment by subogero** [comment]
Cool

**Comment by perlpunk** [comment]
released YAML::XS 0.63 \o/

@godsarmy since you got a different error message and not "out of memory" - If you still get the error, please reopen

**Comment by subogero** [comment]
Thanks for the release.

**Comment by perlpunk** [comment]
So, three years later I finally found time to look into the remaining leak and fixed it \o/

#93
