### ISSUE TITLE
roundtrips with string with utf8 and control characters

### ISSUE THREAD

**Issue by rurban** [ingydotnet/yaml-libyaml-pm#46]
dumping a yml with strings containing utf8 or control characters lead to strings being dumped without the single or double quotes, which leads to errors when loading it.

i.e. Moose/META.yml contains 

    - "יובל קוג'מן (Yuval Kogman) <nothingmuch@woobling.org>"
    - 'Lars Dɪᴇᴄᴋᴏᴡ 迪拉斯 <daxim@cpan.org>'

which will be dumped as Moose/MYMETA.yml:

    - ×<U+0099>×<U+0095>×<U+0091>×<U+009C> ×§×<U+0095>×<U+0092>'×<U+009E>×<U+009F> (Yuval Kogman) <nothingmuch@woobling.org>
    - Lars DÉªá´<U+0087>á´<U+0084>á´<U+008B>á´<U+008F>á´¡ è¿ªæ<U+008B><U+0089>æ<U+0096>¯ <daxim@cpan.org>

and then this yaml cannot be loaded anymore.

**Comment by perlpunk** [comment]
Is there a way to reproduce this? I just took a random module which has a Build.PL, and the generated file looks ok to me.
Module::Build 0.421

**Comment by rurban** [comment]
No time this weekend. I'll send a testcase, how it happened exactly

**Comment by perlpunk** [comment]
Ah, I see, you have to set `PERL_YAML_BACKEND=YAML::XS`. Then I can see the behaviour.
I don't have much experience with YAML::XS and utf8, but I believe this is caused by the open mode `:utf8` in `CPAN::Meta::save()`.
YAML::XS wants the data encoded, so unsetting $layer makes it work.

**Comment by perlpunk** [comment]
reproduce:
```perl
use utf8;
use YAML::XS ();
my $data = [ "יובל קוג'מן (Yuval Kogman) <nothingmuch\@woobling.org>" ];
my $yaml = YAML::XS::Dump($data);
open my $fh, ">:utf8", "test.yaml" or die $!;
print $fh $yaml;
close $fh;
```

**Comment by rurban** [comment]
Thanks a lot @perlpunk. So it's a CPAN::Meta bug. Fixing it there
