### ISSUE TITLE
Question about the perl representation of false

### ISSUE THREAD

**Issue by le-garff-yoann** [ingydotnet/yaml-libyaml-pm#47]
Is it possible to ensure that the parser translates `false` into `0` instead of an empty string ?

**Comment by perlpunk** [comment]
The empty string is perl's default false value, so I don't think there will be an option to support `0`.

Starting with YAML::XS 0.66_001, you can use this:
```perl
local $YAML::XS::Boolean = "JSON::PP"; # or "boolean"
my $data = Load("booltrue: true");
$data->{boolfalse} = JSON::PP::false;
my $yaml = Dump($data);
# boolfalse: false
# booltrue: true
```

See more about this in the docs. Maybe this helps you as the string value of JSON::PP::Boolean and boolean.pm false objects is `0`.

I will close this issue when YAML::XS 0.67 is released, unless there are further questions.
