### ISSUE TITLE
Name used once warnings in BEGIN block

### ISSUE THREAD

**Issue by bingos** [ingydotnet/yaml-libyaml-pm#59]
Name YAML::XS::DumpCode and YAML::XS::UseCode possible typo warnings are generated when YAML::XS::Dump is used in a BEGIN {} block.

> use strict;
> use warnings;
> $|=1;
> BEGIN {
>  require YAML::XS;
>  my $yaml = YAML::XS::Dump( { recent => 'foo' } );
>  print $yaml;
>}

> perl yamlxstest.pl
> ---
> recent: foo
> Name "YAML::XS::UseCode" used only once: possible typo at yamlxstest.txt line 8.
> Name "YAML::XS::DumpCode" used only once: possible typo at yamlxstest.txt line 8.

**Comment by perlpunk** [comment]
thanks, I created PR #60

**Comment by perlpunk** [comment]
fixed in YAML::XS 0.65, thanks
