### ISSUE TITLE
YAML::LibYAML lost VERSION

### ISSUE THREAD

**Issue by twogee** [ingydotnet/yaml-libyaml-pm#8]
cpan shell says

    YAML::LibYAML                 undef      0.47  INGY/YAML-LibYAML-0.47.tar.gz

after 0.51 is installed by

    cpan> install INGY/YAML-LibYAML-0.51.tar.gz

**Comment by fecundf** [comment]
I'm also seeing this; it doesn't prevent install but it does prevent anything that lists any version number of YAML::LibYAML as a prereq from building & installing inside CPAN. Which is blocking me installing some modules that require a certain version-or-higher of this.

This is happening with 0.57, visible in the CPAN shell on both Strawberry Perl 64-bit and ActiveState Perl 64-bit.

I submitted my ActiveState install "pass" to the cpantesters metabase. I don't see my results yet on the site, but do see someone else's similar Straberry Perl results at http://cpantesters.org/cpan/report/e75d2cd9-6bf9-1014-9789-ad208ac59954 (and on that it looks like YAML::Syck has a similar issue with verion coming up as n/a)

**Comment by karenetheridge** [comment]
02packages.details.txt (the master PAUSE index) has:

```
YAML::LibYAML                     undef  N/NA/NAWGLAN/YAML-LibYAML-0.57.tar.gz
YAML::XS                           0.57  N/NA/NAWGLAN/YAML-LibYAML-0.57.tar.gz
YAML::XS::LibYAML                 undef  N/NA/NAWGLAN/YAML-LibYAML-0.57.tar.gz
```

**Comment by ingydotnet** [comment]
Fixed in 0.58. I added a VERSION to YAML::LibYAML.

YAML::LibYAML is internal usage only, and won't get a VERSION.

**Comment by fecundf** [comment]
Installed 0.58 and it shows up as 0.58. Thanks! (I assume you meant
YAML::SAX was internal only thus no version for that one.)


-y

~~~~~

The Moon is Waning Crescent (1% of Full)

**Comment by ingydotnet** [comment]
I meant

YAML::XS::LibYAML is internal usage only, and won't get a VERSION.

Thanks for catching that. And you are welcome. :)
