### ISSUE TITLE
Inconsistency between YAML and YAML::XS in Dump() results

### ISSUE THREAD

**Issue by SanyaZZZ** [ingydotnet/yaml-libyaml-pm#9]
```
$ /opt/drw/bin/perl/perl -MYAML -e 'print Dump( { asd => [ { qwe => "rty", zxc => "vbn" } ] } );'

---
asd:
  - qwe: rty
    zxc: vbn

$ /opt/drw/bin/perl/perl -MYAML::XS -e 'print Dump( { asd => [ { qwe => "rty", zxc => "vbn" } ] } );'

---
asd:
- qwe: rty
  zxc: vbn
```

There is no indent for an array in YAML::XS results, and this dump can't be loaded by YAML::Load().
Versions used: YAML v0.97, YAML::XS v0.52, perl v5.16.3 and 5.18.2

**Comment by rurban** [comment]
Ingy: I'm not sure if you are right here.
The specs say: "Each node must be indented further than its parent node" http://yaml.org/spec/1.2/spec.html#6.1

The samples in the spec also use this indentation for array elements.
I would rather blame libyaml dumper, because it generates unparsable YAML. e.g. by the Perl PP parsers.

Can I fix it there?

**Comment by rurban** [comment]
Fixed with the option IndentlessMap in https://github.com/ingydotnet/yaml-libyaml-pm/pull/43

**Comment by perlpunk** [comment]
@rurban 
Please see
* http://yaml.org/spec/1.2/spec.html#id2799181 8.2.3 Block Nodes
```
[201] seq-spaces(n,c) ::= c = block-out ⇒ n-1
                          c = block-in  ⇒ n
```

* http://yaml.org/spec/1.1/#id931893 10.1.2 Block sequences
```
[197] seq-spaces(n,c) ::= c = block-out ⇒ n-1
                          c = block-in  ⇒ n
```

Both YAML 1.1 and 1.2 allow zero indented sequences.
Like @ingydotnet said, YAML.pm is broken here. Pull requests for YAML.pm welcome.

In general, allowing to configure indendation and other stuff in YAML::XS would be desirable, but I don't like an IndentlessMap option.

> The samples in the spec also use this indentation for seq elements.

Yes, examples use zero indented sequences. So?

Closing...

**Comment by perlpunk** [comment]
Released YAML.pm 1.25_001 which supports zero indented block sequences
